### ISSUE TITLE
Proposal for Improved schemas for optional fields, future values, and record links

### ISSUE THREAD

**Issue by zvictor** [sebastianwessel/surrealdb-client-generator#12]
I am new to SurrealDB and I might have a wrong perception over a thing or two here, but I would like to share my thoughts regarding _optional fields_, _future values_, and _record links_.

---

Given the schema below:
```sql
DEFINE TABLE book SCHEMAFULL;

DEFINE FIELD author ON TABLE book TYPE option<record<author>>;

DEFINE FIELD vendors ON TABLE book TYPE array<object> DEFAULT [];
DEFINE FIELD vendors[*].name ON TABLE book TYPE string;
DEFINE FIELD vendors[*].price ON TABLE book TYPE number;

DEFINE FIELD price ON TABLE book
  VALUE <future> {
    -- whatever code... --
  };
```

We currently generate this:
```ts
const bookInputSchemaGen = z.object({
  author: z.any(),
  price: z.number(),
  vendors: z.array(
    z.object({
      name: z.string(),
      price: z.number(),
    })
  ),
})

// bookOutputSchemaGen is the same as bookInputSchemaGen
```

However,

* Given that `price` is a `VALUE <future>`, we would want it ommited from the input schema.
* Given that `author` is an `option<record>`, we would want it to be optional (and typed as `string`?).

Thus, that would be a better generated schema:
```ts
const bookInputSchemaGen = z.object({
  author: z.optional(z.string()),
  vendors: z.array(
    z.object({
      name: z.string(),
      price: z.number(),
    })
  ),
})

const bookOutputSchemaGen = z.object({
  author: z.any(), // would there be a better type for record links in outputs?
  price: z.number(),
  vendors: z.array(
    z.object({
      name: z.string(),
      price: z.number(),
    })
  ),
})
```

Any thoughts/reactions to that? 🙂

**Comment by sebastianwessel** [comment]
Thanks for the feedback.

Regarding `record`, the correct way would be something like this for Output schema:

```ts
const AuthorAutputSchemaGen = z.object({
  name: z.string(),
  ...other author fields...
})


const bookOutputSchemaGen = z.object({
  author: z.optional(AuthorAutputSchemaGen),
  vendors: z.array(
    z.object({
      name: z.string(),
      price: z.number(),
    })
  ),
})

```


For the Input schema, a record id should be the correct way I guess - something like this:

```ts
const bookInputSchemaGen = z.object({
  author: z.optional(z.object({ tb: z.string(), id: z.string() })),
  vendors: z.array(
    z.object({
      name: z.string(),
      price: z.number(),
    })
  ),
})
```

Regarding the future, you are right, it should not be part of the input schema in this case.
I created an extra ticket for it (#13). In general, the Value field should be respected more (like setting to current datetime).

**Comment by zvictor** [comment]
Using futures is becoming more complicated than I expected. Even without this lib I am struggling to create documents that use them.

I am getting errors like this:
```haskell
There was a problem with the database: Found NONE for field `price`, with record `book:b5miluxp6pvmi7mpvpbl`, but expected a object
    at Surreal.create (/node_modules/.pnpm/surrealdb.js@1.0.0-beta.9/node_modules/surrealdb.js/src/surreal.ts:470:24)
```

I tried adding `READONLY` to the schema but surrealdb still requires me to set `price` when creating a new document.

Anyway, this is not a problem of this library. I am just sharing it as I realize I need to first figure out how to handle surrealdb.

**Comment by zvictor** [comment]
Okay, so the problem I was having with futures is over.
When using `VALUE <future>`, one cannot specify any TYPE other than `any` (https://github.com/surrealdb/surrealdb/issues/2533 is tracking this issue).

For more info on that, check [discord](https://discord.com/channels/902568124350599239/1018618253695795261/1250104075455037502).

---

Also, the problem I was having with the field `price` in the previous message was caused by a bad schema definition for the array of objects I was using.

---

Both errors have been fixed. We can now go back to the main points of this issue. Sorry for the mess. 😊

**Comment by sebastianwessel** [comment]
Thank's for your feedback.
Generating the schemas for array items is currently not working correctly.
I will take a look into this, based on your feedback.

**Comment by sebastianwessel** [comment]
Hey @zvictor 

I'm currently improving the array handling, and I was wondering if your definition is correct.

You have this definition with`vendors[*].`

```
DEFINE FIELD vendors ON TABLE book TYPE array<object> DEFAULT [];
DEFINE FIELD vendors[*].name ON TABLE book TYPE string;
DEFINE FIELD vendors[*].price ON TABLE book TYPE number;
```

But according to [the SurrealDB documentation](https://surrealdb.com/docs/surrealdb/surrealql/statements/define/field#array-type), it should look like this (if I'm not wrong):

```
DEFINE FIELD vendors ON TABLE book TYPE array<object> DEFAULT [];
DEFINE FIELD vendors.name ON TABLE book TYPE string;
DEFINE FIELD vendors.price ON TABLE book TYPE number;
```

**Comment by zvictor** [comment]
Nope! `vendors.name` has failed to me, but both `vendors[*].name` and `vendors.*.name` work.

I kept the `[*]` version over `*` just because that's what AI spitted out  while I was having some errors with the `vendors.*.name` version (probably because of something else I was doing wrong).

If that's important to you, let me know and I can take a look at my schemas again, double checking the use of this syntax.

**Comment by sebastianwessel** [comment]
Yes, would be great if you can try it out - maybe I will ask in the SurrealDB discord as well for the official answer.

If there is a need for `[*]` - or it is allowed, it must be explicit handled.

**Comment by sebastianwessel** [comment]
@zvictor the new version 2.3.0 is released.

It should now have a better handling for arrays, has improved assert handling, fixed some connection bug and small issues.

If you like, try it out 😜

**Comment by sebastianwessel** [comment]
Version 2.5 is out and should a good working version.

I will close this ticket and if there are some issues, we will track them as own (small) tickets.

Thanks @zvictor for your awesome feedback!
