### ISSUE TITLE
npx surql-gen missdirected.

### ISSUE THREAD

**Issue by AurimarL** [sebastianwessel/surrealdb-client-generator#67]

**Comment by AurimarL** [comment]
Hello, i had made a Fork of this project and published my changes to npm package, now the original surql-gen lost his original call.

if you use *npx surql-gen*, i will call this package:
https://www.npmjs.com/package/surql-gen
and not
https://www.npmjs.com/package/@sebastianwessel/surql-gen

**Comment by sebastianwessel** [comment]
Well done mate 🤮!

Thanks for at least let us know.

**Comment by sebastianwessel** [comment]
@AurimarL any chance that you maybe publish your fork with your own scope, instead to simply remove my scope and unplublish/revert the unscoped version from npm?

So, that we can get at least some time to update our documentation and users are able to read it and change their cmd in future?

The idea behind publishing with scope was, to not block something official from surrealdb, but now I regret it

**Comment by AurimarL** [comment]
i didn't unpublish it because someone else could do the same, and informing you that once i unpublish you should publish again to prevent that happen again.

**Comment by AurimarL** [comment]
i dont mind using my own scope, still learning bro... this could be way worse.

**Comment by AurimarL** [comment]
![Captura de ecrã 2024-10-28 201257](https://github.com/user-attachments/assets/e497778b-01e1-4dbe-8d87-b8b268bb42f1)
Done.
