### ISSUE TITLE
Does not support for "IF NOT EXISTS" syntax for DEFINE statements

### ISSUE THREAD

**Issue by lylejohnson** [sebastianwessel/surrealdb-client-generator#7]
Version 1.1.3 of `surql-gen` does not support the "IF NOT EXISTS" syntax for `DEFINE` statements,  introduced in SurrealDB version 1.3.0. It errors out as follows:
```
[Error: Parse error: Failed to parse query at line 5 column 16 expected ON
  |
5 | DEFINE USER IF NOT EXISTS myusername ON DATABASE PASSWORD 'secret' ROLES EDITOR;
  |
] {
  code: 'GenericFailure'
}

**Comment by sebastianwessel** [comment]
The issue should now be resolved.
See [Version 2 Release Note](https://github.com/sebastianwessel/surrealdb-client-generator/releases/tag/2.0.0).
